name: Test

on:
   push:
      branches: [master, v2]
   pull_request:
      branches: [master, v2]
   workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup NodeJS Environment
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.json
          
      - name: Install Dependencies
        run: pnpm i
      
      - name: Run Tests
        run: pnpm run test
