name: Test

on:
   push:
      branches: [master, v2]
   pull_request:
      branches: [master, v2]
   workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - latest

    name: NodeJS ${{ matrix.node_version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
 
      - uses: pnpm/action-setup@v2.2.4
        with:  
          version: latest
          
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      
      - name: Run Tests
        run: pnpm run test:prod
