name: Test

on:
   push:
      branches: [master, v2]
   pull_request:
      branches: [master, v2]
   workflow_call:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 12
          - 14
          - 16
          - 18
          - latest
        architecture:
          - x64

    name: NodeJS ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
            
      - uses: pnpm/action-setup@v2.0.1   
        with:  
          version: latest
          
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      
      - name: Run Tests
        run: pnpm run test
